# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/korch/',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/korch/tree/master/',
                'lib_path': 'korch'},
  'syms': { 'korch.nn': { 'korch.nn.History': ('nn.html#history', 'korch/nn.py'),
                          'korch.nn.History.aggregate': ('nn.html#history.aggregate', 'korch/nn.py'),
                          'korch.nn.History.log_dict': ('nn.html#history.log_dict', 'korch/nn.py'),
                          'korch.nn.Module': ('nn.html#module', 'korch/nn.py'),
                          'korch.nn.Module.__init__': ('nn.html#module.__init__', 'korch/nn.py'),
                          'korch.nn.Module.compile': ('nn.html#module.compile', 'korch/nn.py'),
                          'korch.nn.Module.evaluate': ('nn.html#module.evaluate', 'korch/nn.py'),
                          'korch.nn.Module.fit': ('nn.html#module.fit', 'korch/nn.py'),
                          'korch.nn.Module.train_step': ('nn.html#module.train_step', 'korch/nn.py'),
                          'korch.nn.Module.validation_step': ('nn.html#module.validation_step', 'korch/nn.py'),
                          'korch.nn.get_pbar_description_from_batch_metrics': ( 'nn.html#get_pbar_description_from_batch_metrics',
                                                                                'korch/nn.py')}}}