# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/korch/',
                'doc_host': 'https://Jorgvt.github.io',
                'git_url': 'https://github.com/Jorgvt/korch/tree/master/',
                'lib_path': 'korch'},
  'syms': { 'korch.core': { 'korch.core.History': ('core.html#history', 'korch/core.py'),
                            'korch.core.History.aggregate': ('core.html#history.aggregate', 'korch/core.py'),
                            'korch.core.History.log_dict': ('core.html#history.log_dict', 'korch/core.py'),
                            'korch.core.Module': ('core.html#module', 'korch/core.py'),
                            'korch.core.Module.__init__': ('core.html#module.__init__', 'korch/core.py'),
                            'korch.core.Module.compile': ('core.html#module.compile', 'korch/core.py'),
                            'korch.core.Module.evaluate': ('core.html#module.evaluate', 'korch/core.py'),
                            'korch.core.Module.fit': ('core.html#module.fit', 'korch/core.py'),
                            'korch.core.Module.train_step': ('core.html#module.train_step', 'korch/core.py'),
                            'korch.core.Module.validation_step': ('core.html#module.validation_step', 'korch/core.py'),
                            'korch.core.get_pbar_description_from_batch_metrics': ( 'core.html#get_pbar_description_from_batch_metrics',
                                                                                    'korch/core.py')}}}