# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Module": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://Jorgvt.github.io/korch/"

git_url = "https://github.com/Jorgvt/korch/tree/master/"

def custom_doc_links(name): return None
