# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['Module']

# Cell
#export
import torch
import torch.nn as nn
from tqdm.auto import tqdm

# Internal Cell
#exporti
def get_pbar_description_from_batch_metrics(batch_metrics, prefix=""):
    description = ""
    for name, value in batch_metrics.items():
        description += f'{prefix}{name}: {value:.2f} '
    return description[:-1]

# Cell
class Module(nn.Module):
    def __init__(self, **kwargs):
        super(Module, self).__init__(**kwargs)

    def train_step(self, batch):
        self.train()

        inputs, labels = batch
        self.optimizer.zero_grad()
        outputs = self(inputs)
        loss = self.loss_fn(outputs, labels)
        loss.backward()
        self.optimizer.step()

        ## Obtain metrics if needed
        if self.metrics is not None:
            metrics = self.metrics(outputs, labels)
            metrics = {name:value.item() for name, value in metrics.items()}
            metrics['Loss'] = loss.item()
        else:
            metrics = {'Loss':loss.item()}
        return metrics

    def validation_step(self, batch):
        self.eval()

        inputs, labels = batch
        with torch.no_grad():
            outputs = self(inputs)
            loss = self.loss_fn(outputs, labels)

        ## Obtain metrics if needed
        if self.metrics is not None:
            metrics = self.metrics(outputs, labels)
            metrics = {name:value.item() for name, value in metrics.items()}
            metrics['Loss'] = loss.item()
        else:
            metrics = {'Loss':loss.item()}
        return metrics

    def fit(self, trainloader, epochs, validationloader=None):
        for epoch in tqdm(range(epochs), desc='Epochs', position=0):
            pbar = tqdm(enumerate(trainloader), total=len(trainloader), position=1, leave=False)
            for batch_idx, batch in pbar:
                batch_metrics = self.train_step(batch)
                pbar.set_description(get_pbar_description_from_batch_metrics(batch_metrics))
            if validationloader is not None:
                pbar = tqdm(enumerate(validationloader), total=len(validationloader), position=2, leave=False)
                for batch_idx, batch in pbar:
                    batch_metrics = self.validation_step(batch)
                    pbar.set_description(get_pbar_description_from_batch_metrics(batch_metrics, 'Val_'))
            self.metrics.reset()

    def compile(self, loss=None, optimizer=None, metrics=None):
        """
        metrics: torchmetrics.MetricCollection
        """
        self.loss_fn = loss
        self.optimizer = optimizer
        self.metrics = metrics

    def evaluate(self, dataloader):
        results = [self.validation_step(batch) for batch in tqdm(dataloader, total=len(dataloader))]
        return sum(results)/len(results)